apiVersion: v1
kind: Service
metadata:
  name: inventory
  namespace: dapr-go-hero-inventory
  labels:
    app: inventory
spec:
  type: LoadBalancer
  selector:
    app: inventory
  ports:
    - name: api
      port: 3000
      targetPort: 3000
