apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: dapr-go-hero
  labels:
    app: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          # renovate: datasource=docker depName=openzipkin/zipkin-slim
          image: openzipkin/zipkin-slim:3.6.1
          ports:
            - containerPort: 9411
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: dapr-go-hero
spec:
  selector:
    app: zipkin
  ports:
    - port: 9411
      targetPort: 9411
